### PR TITLE
5.X compatible version 

### PR DESCRIPTION
**Pull request by Shnoulle**
Checked working version, sponsored by [Université Toulouse III - Paul Sabatier](https://www.univ-tlse3.fr/)

I add getGlobalBasePermissions too, was in 3.0.0 LimeSurvey version.
But this broke compatibility i think ? I think i can check if it's set or not : not set for this user : can log in. Set and to 0 : can not login.

### CODE REVIEW

**Comment by Shnoulle** [comment]
PS : work on PHP7.4 with debug mode set \o/ 
Usage of composer.

**Comment by Shnoulle** [comment]
> But this broke compatibility i think ? I think i can check if it's set or not : not set for this user : can log in. Set and to 0 : can not login.

Fixed : if not set in Permssion, set it to true at 1st login.

**Comment by goyome** [comment]
Thanks a lot to you and Université Toulouse III - Paul Sabatier for this PR. 
We're going to test it next week and keep you posted.

**Comment by Shnoulle** [comment]
Yes ,
Can you test particullary the previous account ? If Permission is updated to allow login.
I think it still work on 2.73 version, but not tested too.

(on peuw continuer en Français au cas ou)

**Comment by schoubi** [comment]
Works flawlessly on [Version 5.2.12+220131] 👍

**Comment by goyome** [comment]
Thanks again for your work. It works well on our test instance :+1:

**Comment by Shnoulle** [comment]
> Thanks again for your work. It works well on our test instance 👍

LimeSurvey version ?

**Comment by goyome** [comment]
Version 5.2.5+211207

**Pull request merged**
